* FRAMEWORK PARA LA AUTOMATIZACIÓN DE PRUEBAS EN EW
** Diagrama de despligue
*** Instancia única maestro-esclavo
*** Un maestro con uno o varios esclavos
**** Diagrama de arquitectura de red
** Anexos 
*** Guia de instalación 
**** COMMENT Pasos previos 
***** Master 
****** Definir variables de ambiente
Los pasos previos nos van pérmitir definir accesos rápidos a los directorios de trabajos :
- $TFG es el directorio donde tengo almancenado mi trabajo fin de grado
- LAVA_MASTER_CONF es el directorio donde reside toda la configuración referente a lava. En el caso de 
de la instalación única el directorio contiene los ficheros de configuración tanto del maestro como del esclavo
Por lo tanto en el host que hace de maestro el directorio la configuración del mismo.
- $LAVA_MASTER_DISPATCHER es el directorio donde se almacena los templates : device-types y device-dictionaries.
- $LAVA_MASTER_LOG es el directorio con los fichero de log
- $LAVA_MASTER_FRONTEND_SRC directorio con el código del frontent
- $LAVA_MASTER_FRONTEND_TEMPLATES directorio con las plantillas html

**** Instancia única maestro-esclavo
El método de instalación básico y recomendado por Linaro consiste en instalar dentro de un host
tanto el maestro como el esclavo. Al host tambíen será necesario conectarle los DUTs.
Este método no precisa de configuraciones adicionales a las instaladas por defecto.
Para familiarizarmos con los diferentes componentes de LAVA se optó por una instalación básica.
No se recomienda llevar acabo este tipo de instalación en producción.
Necesitamos tener acceso a los paquetes del repositorio de LAVA antes de empezar con la 
instalación. Los comandos que debemos de ejecutar son :
#+BEGIN_SRC shell
# instalacion **wget**
sudo apt install -y wget
# importamos la clave del repositorio
wget --quiet -O - https://apt.lavasoftware.org/lavasoftware.key.asc | sudo apt-key add -
# habilitamos la descarga de paquetes del repositorio 
RELEASE=$(lsb_release -cs)
echo "https://apt.lavasoftware.org/release ${RELEASE}" main | sudo tee  /etc/apt/sources.list.d/lavadg.list
#+END_SRC
Para instalar LAVA dentro del host ejecutaremos dentro de un términal :
#+BEGIN_SRC shell
sudo apt update
sudo apt install postgresql
sudo apt install lava
#+END_SRC



** Seguridad
*** HTTPs
*** Backups

* Agenda
** TODO Root
Explicar que es necesario emplear el usuario root para mover los ficheros con el usuario normal
no vale.
** TODO Registro del worker
Pasos a seguir

